app/Http/routes.php
<?php

use Illuminate\Http\Request;

/*
  |--------------------------------------------------------------------------
  | Application Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register all of the routes for an application.
  | It's a breeze. Simply tell Laravel the URIs it should respond to
  | and give it the controller to call when that URI is requested.
  |
*/

Route::group(['middleware' => 'web'], function () {

    Route::get('/', 'BlogController@showIndex')->name('index');
    Route::get('/search', 'BlogController@getSearch');
    Route::get('/date', 'BlogController@getDate');

    Route::resource('post','PostController');
    Route::post('/post/{id}/vote', ["uses" => 'PostController@vote', "as" => "post.vote"]);
    Route::post('/comment/{id}/vote', ["uses" => 'CommentController@vote', "as" => "comment.vote"]);

    Route::resource('comment','CommentController');
    Route::resource('attachment','AttachmentController');

    Route::controller('gallery', 'GalleryController');

    Route::controller('user', 'UserController');

});

Route::auth();
Route::get('/home', 'HomeController@index');

resources/views/gallery.blade.php
@extends('layouts.main')

@section('title')
    Gallery
@endsection

@section('content')
    <h1>Gallery:</h1>
    @foreach($attachments as $attachment)
        @if(preg_match('/image\/\w+/', $attachment->type) and $attachment->show_in_gallery)
            <a href="{{url("/post/".$attachment->post_id)}}"><img class="picture" src="{{ url($attachment->path) }}" style="max-width: 200px; max-height: 200px" /></a>
        @endif
    @endforeach

@endsection

resources/views/header.blade.php
<div class="wrapper">
    <div id="header">
	<h1>Phlog</h1>
	<nav id="navbar">
	    <ul>
		<li><a href="{{url("/")}}">Home</a> </li>
		<li><a href="{{url("/gallery")}}">Gallery</a> </li>
		@if (Auth::check())
		    @if (Auth::user()->is_admin)
			<li><a href="{{ url('/post/create') }}">New post</a></li>
		    @else
			<li><a></a></li>
		    @endif
		    <li><a href="{{ url('/logout') }}">Logout</a></li>
		@else
		    <li><a href="{{url("/register")}}">Sign up</a> </li>
		    <li><a href="{{url("/login")}}">Login</a> </li>
		@endif
	    </ul>
	</nav>
	@if (Auth::check())
	    Logged in as: {{ Auth::user()->name }}
	@endif
    </div>
</div>

resources/views/home.blade.php
@extends('layouts.main')

@section('content')
    <div id="home">
	<h3>You are now logged in!</h3>
    </div>
@endsection

resources/views/index.blade.php
@extends("layouts.main")

@section("title")
    Best Blog Ever!
@endsection
@section("content")
    <h1>Blog posts: </h1>
    <div id="blog">
        @if(count($blog_posts) > 0)
    @foreach($blog_posts as $blog_post)

        <article class="blogpost">
            <table class="up_down_vote">
                <tr>
                    <td><a data-type="post" data-id="{{ $blog_post->id }}" class="vote upvote"></a></td>
                    <td></td>
                </tr>
                <tr>
                    <td>
                        <b>{{$blog_post->getVoteCount()}}</b>
                    </td>
                    <td>
                        <h2><a href="{{url("/post/".$blog_post->id)}}">{{$blog_post->title}}</a></h2>
                    </td>
                </tr>
                <tr>
                    <td>
                        <a data-type="post" data-id="{{ $blog_post->id }}" class="vote downvote"></a>
                    </td>
                    <td></td>
                </tr>
            </table>
                {!! Markdown::convertToHtml(str_limit($blog_post->postdata, $limit = 300, $end = '...')) !!}
            <b>Posted by: {{$blog_post->user->name}}</b>
            <b> At: {{$blog_post->created_at}}</b>
            @if($blog_post->updated_at != $blog_post->created_at)
                <b> Updated at: {{$blog_post->updated_at}}</b>
            @endif<br>
            <b>{{$blog_post->views}} view{{$blog_post->views != 1 ? "s" : "" }}</b>
            <b> and {{count($blog_post->comments)}} comment{{ count($blog_post->comments) != 1 ? "s" : "" }}</b>
        </article>
        <hr/>
    @endforeach
        @else
            @if(app('request')->input('search_query'))
                <div class="no_content_message">There are no posts containing: {{ app('request')->input('search_query') }}</div>
            @else
                <div class="no_content_message">There is nothing here yet.</div>
            @endif
        @endif
        {!! $blog_posts->render() !!}
    </div>
    @include('partial.sidebar')

    <script type="text/javascript">
        var upvote_btns = document.getElementsByClassName('vote');
        for (i = 0; i < upvote_btns.length; i++) {
            upvote_btns[i].addEventListener('click', function(event) {
                var thingtype = event.target.getAttribute('data-type');
                var thingid = event.target.getAttribute('data-id');

                var url = (thingtype == "post" ? "/post/" : "/comment/")
                        + thingid
                        + '/vote';

                var is_upvote = /(?:^|\s)upvote(?:\s|$)/.test(event.target.className);

                var ajax = new XMLHttpRequest();
                ajax.open("POST", url, true);
                var data = new FormData();
                data.append("_token", "{{ Session::token() }}");
                data.append("vote",(is_upvote ? "1" : "0"));
                ajax.send(data);
                ajax.onload = function () {
                    var response = JSON.parse(ajax.responseText);

                    if (!response.vote_succeded) {
                        // display errors
                        var error_section = document.getElementById("errors");
                        var error_node = document.createElement("b");
                        error_node.classList.add("error");
                        error_node.innerHTML = response.errors;
                        while (error_section.firstChild) {
                            error_section.removeChild(error_section.firstChild);
                        }
                        error_section.appendChild(error_node);
                        window.scrollTo(0,0);
                    }

                    var amount = 0;
                    if (response.response_type == 1) { amount = 1; }
                    else if (response.response_type == 2) { amount = -1; }
                    else if (response.response_type == 3) { amount = 2; }
                    if (is_upvote) {
                        var vote_counter = event.target
                                .parentElement
                                .parentElement
                                .nextElementSibling
                                .childNodes[1]
                                .childNodes[1];
                        vote_counter.innerHTML = Number(vote_counter.innerHTML) + amount;

                    } else {
                        amount = amount * -1;
                        var vote_counter = event.target
                                .parentElement
                                .parentElement
                                .previousElementSibling
                                .childNodes[1]
                                .childNodes[1];
                        vote_counter.innerHTML = Number(vote_counter.innerHTML) + amount;
                    }
                }
            });
        }
    </script>
@endsection

resources/views/newpost.blade.php
@extends('layouts.main')

@section('content')
    <form @if($update)
 action="{{ route('post.update',[$blog_post->id]) }}" method="post"
    @else
 action="{{ route('post.store') }}" method="post"
    @endif
 id="newpostform"  enctype="multipart/form-data">
	<table class="newpost">
	    <h1>New Post:</h1>
	    {!! csrf_field() !!}
	    @if ($update)
		<input name="_method" value="PUT" type="hidden" />
	    @endif
	    <tr>
		<th>
		    <label for="title">Title:</label>
		</th><td>
		    <input type="text" name="title" id="title" value="{{$blog_post->title or ""}}">
		</td>
	    </tr>
	    <tr>
		<th>
		    <label for="postdata">Text:</label>
		</th>
		<td>
		    <textarea name="postdata">{{$blog_post->postdata or ""}}</textarea>
		</td>
	    </tr>
	    <tr>
		<th>
		    <label for="image">File:</label>
		</th>
		<td>
		    <div id="attachments">
			<input name="images[]" type="file" />
		    </div>
		    <input name="attachment" type="button" id="add_attachment" value="add attachment">
		    @if(isset($blog_post) and count($blog_post->attachments) > 0)
			<table class="edit_attachments">
			    <td>Show in gallery | </td>
			    <td>Attachments:</td>
			    @foreach ($blog_post->attachments as $attachment)
				<input type="hidden" name="attachment_ids[]" value="{{ $attachment->id }}" />
				<tr>
				    <td><input type="checkbox" name="attachments_show_in_gallery_{{ $attachment->id }}"
					       @if($attachment->show_in_gallery)
					       checked="checked"
					       @endif
					></input></td>
				    <td><a href="{{ url($attachment->path) }}">{{ $attachment->path }}</a></td>
				    <td><button class="delete_attachment" type="button" data-parent="{{ $attachment->id }}">Delete</button></td>
				</tr>
			    @endforeach
			</table>
				    @endif
				    </td>
	    </tr>
	    <tr>
		<th></th>
		<td>
		    <input type="submit" value="Post">
		</td>
	    </tr>
	</table>
    </form>
    <script type="text/javascript">
     var btn_add_attachment = document.getElementById("add_attachment");
     btn_add_attachment.addEventListener("click", function() {
	 var file_attachment_upload = document.createElement("input");
	 file_attachment_upload.setAttribute('type','file');
	 file_attachment_upload.setAttribute('name','images[]');
	 var div_attachments = document.getElementById("attachments");
	 div_attachments.appendChild(file_attachment_upload);
     });
    </script>

    <script type="text/javascript">
	var delete_attachment_btns = document.getElementsByClassName('delete_attachment');
	for(i=0; i<delete_attachment_btns.length; i++){
						  delete_attachment_btns[i].addEventListener('click', function (event) {
						  var conf = confirm("Are you sure you want to delete this attachment?");
						  if(conf){
						  var r = new XMLHttpRequest();
						  var id = event.target.getAttribute("data-parent");
						  r.open("POST", "/attachment/" + id + "/", true);
						  r.setRequestHeader('X_CSRF_TOKEN', '{{ Session::token() }}');
						  var data=new FormData();
						  data.append("_token", "{{ Session::token() }}");
						  data.append("_method", "DELETE");
						  r.send(data);

						  event.target.parentElement.parentElement.remove();
	}
						  });
	}
    </script>
@endsection

resources/views/viewpost.blade.php
@extends('layouts.main')

@section('title')
{{ $blog_post->title }}
@endsection

@section('content')
    <article class="blogpost">

	<table class="up_down_vote">
	    <tr>
		<td><a data-type="post" data-id="{{ $blog_post->id }}" class="vote upvote"></a></td>
		<td></td>
	    </tr>
	    <tr>
		<td>
		    <b>{{$blog_post->getVoteCount()}}</b>
		</td>
		<td>
		    <h2>{{ $blog_post->title }}</h2>
		</td>
	    </tr>
	    <tr>
		<td>
		    <a data-type="post" data-id="{{ $blog_post->id }}" class="vote downvote"></a>
		</td>
		<td></td>
	    </tr>
	</table>


	@foreach($blog_post->attachments as $attachment)
	    @if(preg_match('/image\/\w+/', $attachment->type))
		<img src="{{ url($attachment->path) }}" style="max-width: 500px;" />
	    @endif
	@endforeach
	<br/>

	@if(count($blog_post->attachments) > 0)
	    <b>Attachments:</b> <br/>
	    <ul class=attachmentlist>
		@foreach ($blog_post->attachments as $attachment)
		    <li><a href="{{ url($attachment->path) }}">{{ $attachment->path }}</a></li>
		@endforeach
	    </ul>
	@endif


	{!! $blog_post->markdown !!}
	<b>Posted at: {{ $blog_post->created_at }}</b><br>
	@if($blog_post->updated_at != $blog_post->created_at)
	    <b>Updated at: {{ $blog_post->updated_at }}</b><br>
	@endif
	<b>By: {{ $blog_post->user->name }}</b>
    </article>
    <hr/>
    @if(Auth::check())
	<button class="new_comment">comment</button>
	<div class="comment_area"> </div>
	@if(Auth::user()->is_admin)
	    <a class="edit_post" href="{{ route('post.edit',[$blog_post->id]) }}">Edit post</a>
	    <form action="{{ route('post.destroy',[$blog_post->id]) }}" method="POST">
		{!! csrf_field() !!}
		{!! method_field('DELETE') !!}
		<input type="submit" value="Delete post"/>
	    </form>
	@endif
    @endif
    @include('partial.comment',["comments" => $comments])
    <script type="text/javascript">
     var post_id = {{ $blog_post->id }};
     var new_comment_btns = document.getElementsByClassName('new_comment');
     for (i = 0; i < new_comment_btns.length; i++) {

	 new_comment_btns[i].addEventListener('click', function (event) {
	     
	     var comment_area = event.target;

	     comment_area = comment_area.nextElementSibling;

	     // find next comment area
	     while (!(/(?:^|\s)comment_area(?:\s|$)/.test(comment_area.className))) {
		 if (comment_area = comment_area.nextElementSibling) {
		     break;
		 }
	     }

	     if (comment_area.childNodes.length > 1) {
		 return;
	     }
	     // generate form
	     var comment_form = document.createElement('form');
	     comment_form.setAttribute('method','post');
	     comment_form.setAttribute('action','{{ route('comment.store') }}');
	     comment_form.setAttribute('class','newcommentform');

	     // generate form fields
	     var csrf_input = document.createElement('input');
	     csrf_input.setAttribute('type','hidden');
	     csrf_input.setAttribute('name','_token');
	     csrf_input.setAttribute('value','{{ Session::token() }}');

	     var post_id_input = document.createElement('input');
	     post_id_input.setAttribute('type','hidden');
	     post_id_input.setAttribute('name','post_id');
	     post_id_input.setAttribute('value',post_id);

	     // add comment id if set
	     console.log(event.target);
	     if (event.target.hasAttribute('data-parent')) {

		 var comment_id = document.createElement('input');
		 comment_id.setAttribute('type','hidden');
		 comment_id.setAttribute('name','comment_id');
		 comment_id.setAttribute('value',event.target.getAttribute('data-parent'));
		 comment_form.appendChild(comment_id);
	     } else {
		 console.log("no parent found!");
	     }

	     var textarea_input = document.createElement('textarea');
	     textarea_input.setAttribute('name','comment');
	     textarea_input.setAttribute('placeholder','Type a comment...');
	     var submit_input = document.createElement('input');
	     submit_input.setAttribute('type','submit');
	     submit_input.setAttribute('value','Comment');

	     comment_form.appendChild(csrf_input);
	     comment_form.appendChild(post_id_input);
	     comment_form.appendChild(textarea_input);
	     comment_form.appendChild(submit_input);

	     comment_area.appendChild(comment_form);
	 });
     }
    </script>

    <script type="text/javascript">
     var delete_comment_btns = document.getElementsByClassName('delete_comment')
     for(i = 0; i < delete_comment_btns.length; i++){
	 delete_comment_btns[i].addEventListener('click', function (event) {
	     var conf = confirm("Are you sure you want to delete this comment?");
	     if (conf){
		 var r = new XMLHttpRequest();
		 r.open("POST", "{{ url('/comment/') }}/" + event.target.getAttribute("data-parent"), true);
		 r.setRequestHeader('X-CSRF-TOKEN','{{ Session::token() }}');
		 var data=new FormData();
		 data.append("_token", "{{ Session::token() }}");
		 data.append("_method", "DELETE");
		 r.send(data);

		 // delete comment on client side
		 var commentbox = event.target.parentElement;

		 var newcontent = document.createElement('p');
		 newcontent.className = "comment_content";
		 newcontent.innerHTML = "[Deleted]";

		 while (commentbox.firstChild) {
		     commentbox.removeChild(commentbox.firstChild);
		 }

		 commentbox.appendChild(newcontent);
	     }
	 });
     }
    </script>
    <script type="text/javascript">
     var upvote_btns = document.getElementsByClassName('vote');
     for (i = 0; i < upvote_btns.length; i++) {
	 upvote_btns[i].addEventListener('click', function(event) {
	     var thingtype = event.target.getAttribute('data-type');
	     var thingid = event.target.getAttribute('data-id');

	     var url = (thingtype == "post" ? "/post/" : "/comment/")
		     + thingid
		     + '/vote';

	     var is_upvote = /(?:^|\s)upvote(?:\s|$)/.test(event.target.className);

	     var ajax = new XMLHttpRequest();
	     ajax.open("POST", url, true);
	     var data = new FormData();
	     data.append("_token", "{{ Session::token() }}");
	     data.append("vote",(is_upvote ? "1" : "0"));
	     ajax.send(data);
	     ajax.onload = function () {
		 var response = JSON.parse(ajax.responseText);

		 if (!response.vote_succeded) {
		     // display errors
		     var error_section = document.getElementById("errors");
		     var error_node = document.createElement("b");
		     error_node.classList.add("error");
		     error_node.innerHTML = response.errors;
		     while (error_section.firstChild) {
			 error_section.removeChild(error_section.firstChild);
		     }
		     error_section.appendChild(error_node);
		     window.scrollTo(0,0);
		 } 
		 
		 var amount = 0;
		 if (response.response_type == 1) { amount = 1; }
		 else if (response.response_type == 2) { amount = -1; }
		 else if (response.response_type == 3) { amount = 2; }
		 if (is_upvote) {
		     var vote_counter = event.target
					     .parentElement
					     .parentElement
					     .nextElementSibling
					     .childNodes[1]
					     .childNodes[1];
		     vote_counter.innerHTML = Number(vote_counter.innerHTML) + amount;

		 } else {
		     amount = amount * -1;
		     var vote_counter = event.target
					     .parentElement
					     .parentElement
					     .previousElementSibling
					     .childNodes[1]
					     .childNodes[1];
		     vote_counter.innerHTML = Number(vote_counter.innerHTML) + amount;
		 }
	     }
	 });
     }
    </script>
@endsection